<?php

namespace Enhavo\Component\Cli\Subroutine;

use Enhavo\Component\Cli\AbstractSubroutine;
use Enhavo\Component\Cli\SubroutineInterface;
use Enhavo\Component\Cli\Task\DeleteNodeModulesDir;
use Enhavo\Component\Cli\Task\DeletePublicBuild;
use Enhavo\Component\Cli\Task\DeletePublicBundles;
use Enhavo\Component\Cli\Task\DeletePublicJs;
use Enhavo\Component\Cli\Task\DeleteVarCacheDir;
use Enhavo\Component\Cli\Task\DeleteVarMediaDir;
use Enhavo\Component\Cli\Task\DeleteVendorDir;
use Symfony\Component\Console\Command\Command;

class DeleteAutogeneratedDirs extends AbstractSubroutine implements SubroutineInterface
{
    public function __invoke(): int
    {
        (new DeleteVendorDir($this->input, $this->output, $this->questionHelper))();
        (new DeleteNodeModulesDir($this->input, $this->output, $this->questionHelper))();
        (new DeleteVarCacheDir($this->input, $this->output, $this->questionHelper))();
        (new DeleteVarMediaDir($this->input, $this->output, $this->questionHelper))();
        (new DeletePublicBuild($this->input, $this->output, $this->questionHelper))();
        (new DeletePublicBundles($this->input, $this->output, $this->questionHelper))();
        (new DeletePublicJs($this->input, $this->output, $this->questionHelper))();

        return Command::SUCCESS;
    }
}
