name: Continuous Integration

on:
    push:
    pull_request:

jobs:
    phpunit:
        runs-on: ubuntu-20.04
        name: "PHPUnit on php ${{ matrix.php-versions }}"
        strategy:
            matrix:
                php-versions: ['7.3', '7.4']
            fail-fast: false
        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php-versions }}
                    extensions: json, zlib, curl

            -   name: Get composer cache directory
                id: composercache
                run: echo "::set-output name=dir::$(composer config cache-files-dir)"

            -   name: Cache dependencies
                uses: actions/cache@v2
                with:
                    path: ${{ steps.composercache.outputs.dir }}
                    key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
                    restore-keys: ${{ runner.os }}-composer-

            -   name: Install dependencies
                run: composer install --prefer-dist

            -   name: Setup git
                run: |
                    git config --global user.email "you@example.com"
                    git config --global user.name "Your Name"

            -   name: Run tests
                run: bin/phpunit
