name: Release

on:
    push:
        tags:
            - 'v*.*.*'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 7.3
            -   name: Install dependencies
                run: composer install --prefer-dist
            -   name: Build enhavo.phar
                run: php -d phar.readonly=0 bin/compile
            -   name: Release
                uses: softprops/action-gh-release@v1
                with:
                    files: enhavo.phar
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
